version: '3.8'

services:
  roles-permissions-service:
    build: .
    container_name: roles-permissions-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lavanet_roles
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: lavanet123
    depends_on:
      - postgres
    networks:
      - lavanet-net

  postgres:
    image: postgres:15
    container_name: lavanet-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lavanet123
      POSTGRES_DB: lavanet_roles
    ports:
      - "5432:5432"
    networks:
      - lavanet-net

networks:
  lavanet-net:
    driver: bridge
